### ISSUE TITLE
Julia 0.7-DEV version

### ISSUE THREAD

**Issue by Nosferican** [JuliaStats/StatsModels.jl#52] opened 2018-04-09 19:18 UTC
I was wondering if anyone was working on getting a release of StatsModels for Julia 0.7-DEV. Getting a 0.7-DEV version should be pretty straightforward if we drop the statsmodels.jl DataFrame wrapper and delegations. That should also help towards eventually dropping exclusive dependency on DataFrames and supporting multiple tabular data representations (e.g., getting a stream of Named Tuples for the ModelFrame). One argument if favor of discontinuing future development for 0.x.y versions and focusing on 1.x.y is that no new features are being developed as part of the plans to re-write the Terms representation and ModelBuilder pipeline which will not happen in the near future and most likely after 0.7 / 1.0 is released.

**Comment by kleinschmidt** [comment] 2018-04-10 13:07
I don't know of any active work on this direction (or how hard it would be to make the current implementation work with 0.7-DEV), but it would be a major problem if 0.7/1.0 is released and there isn't _a_ working statsmodels package.

**Comment by nalimilan** [comment] 2018-04-10 13:13
Is there any reason to think that porting the package to 0.7 would be difficult? I wouldn't think so. I'd be inclined to port it with minimal changes, since the deeper improvements (generic streaming API...) are not likely to be ready soon.

**Comment by Nosferican** [comment] 2018-04-10 13:30
The idea is that since new development is not expected to occur until well after 1.x.y, the extra effort to port a compatible version with 0.x.y versions will not add any value. Would any user that wants the new systems need to use 0.x.y versions? Very unlikely. It would also help to migrate code that uses `Nullable` to `Missing` and `Nothing` from Base.

**Comment by nalimilan** [comment] 2018-04-10 13:33
I don't understand. What makes you think we'll be able to stop development soon? Also, what has `Nullable` to do with it?

**Comment by Nosferican** [comment] 2018-04-10 13:45
Releasing a 0.7-DEV version compatible with 0.6 makes sense only if one believes that future developments will occur while users still use 0.6, no? If the future developments will not occur before the release of 1.x.y versions and the ecosystem updated to use 1.x.y versions there is no value to doing a compatible version. If we keep the `DataFrameRegressionModel` for now then it might be worthwhile to do a compatible release since the Julia 0.6 version could break (e.g., StatsBase `stderr` -> `stderror`). If we drop `DataFrameRegressionModel` as a first step to transition to a less `DataFrames` dependent solution, then there wouldn't be a need for a compatible version. The `Nullable` if not mistaken were the go-to solution from Base, but since `Void` changed to `Nothing` and added `Missing`, those are the preferred ways to represent what StatsModels used `Nullable` for.

**Comment by kleinschmidt** [comment] 2018-04-10 14:28
I don't see any reason why we can't support 0.7 while also supporting 0.6. Compat makes that pretty easy.  The only things that nullables are used for are internally in the contrast matrix code which isn't hurting anyone (or even exposed to users, unless they're really digging), so there's no real reason to change that (unless we really feel strongly about not having a nullables dependency since it's moving out of base AFAIK)

**Comment by nalimilan** [comment] 2018-04-10 14:54
I agree with @kleinschmidt. The `stderr` change needs to be backported to 0.6 anyway if StatsBase renames the function. The `Nullable` breakage has been dealt with already, at least for the public API. Finally, I don't see any short-term perspective which would allow us to drop `DataFrameRegressionModel`.

**Comment by kleinschmidt** [comment] 2018-04-16 15:15
See #53

**Comment by kleinschmidt** [comment] 2018-04-16 21:42
closed by 82d6a72

**Closed by kleinschmidt** 2018-04-16 21:42 UTC

**Comment by Nosferican** [comment] 2018-04-19 03:02
It seems like StatsModels is still failing on nightly.

**Comment by kleinschmidt** [comment] 2018-04-19 12:16
master should be okay, unless nightly has changed since then. the badge shows the latest build, which is for #54 (and that failure is just because I can't figure out a way to test for a deprecation warning that works on both 0.6 and 0.7...)
